2024-12-24 19:30:53,471 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "tests_12_4.py", line 26, in test_run
    runner_2 = runner.Runner(123)
  File "/home/ruslan/urbn/assignments/module_12_4/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-24 19:30:53,471 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "tests_12_4.py", line 15, in test_walk
    runner_1 = runner.Runner('runner 1', speed=-2)
  File "/home/ruslan/urbn/assignments/module_12_4/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -2
